"""init

Revision ID: e0aaeedbbb48
Revises: 
Create Date: 2022-08-13 14:36:45.418584

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e0aaeedbbb48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bdate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_200', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_max_orig', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_100', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
